theme: jekyll-theme-slate
title: Liu Ruofan
# Your name to show in the footer
author: Liu Ruofan
description: This is a personal website for Liu Ruofan 
social-network-links:
  email: "kelseyliu1998@gmail.com"
  linkedin: "www.linkedin.com/in/ruofanliu"
