remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Liu Ruofan
# Your name to show in the footer
author: Liu Ruofan
description: This is a personal website for Liu Ruofan 
social-network-links:
  email: "kelseyliu1998@gmail.com"
  linkedin: "www.linkedin.com/in/ruofanliu"
